cargo-features = ["edition2024"]

[package]
name = "disco"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = "4.5.7"
driver = { path = "../driver" }
hal = { path = "../hal" }
core = { path = "../core" }
tokio = { version = "1.36.0", features = ["full"] }
log = "0.4.21"
env_logger = "0.11.3"