cargo-features = ["edition2024"]

[package]
name = "domus"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1.36.0", features = ["full"] }
paste = "1.0.15"
core = { path = "../core" }
driver = { path = "../driver" }

log = "0.4.21"
env_logger = "0.11.3"
